### ISSUE TITLE
Polish translation [1.14.4]

### ISSUE THREAD

**Issue by DarkKnightComes** [Andromander/Nifty#16]
Pastebin link: https://pastebin.com/5uG23rcr

**Comment by Andromander** [comment]
Are you able to make a Pull Request for this? You just Fork this mod and add the file to `src/main/resources/assets/nifty/lang`. The Branch is `1.14.x` when you are selecting which Branch to merge into.

**Comment by DarkKnightComes** [comment]
ok, i'll do that
