### ISSUE TITLE
blockColors crash if another mod has an error

### ISSUE THREAD

**Issue by WenXin20** [Andromander/Nifty#20]
`Minecraft v1.14.4`
`Forge v28.1.111`
`Nifty v2.8`

- If another mod has an error, such as with an invalid config file, Nifty will crash instead of displaying the forge error screen and what went wrong with the other mod/config. 
- This could mislead the player into thinking Nifty is at fault instead of something else.
- Some null checks could help
- [Crash Report](https://gist.github.com/WenXin20/30d8c49b2cbd67ced743bd2c545d9d66)

**Comment by Andromander** [comment]
Fix has been implemented, however is only present on the 1.15.2 versions. Will pin this for 1.14 users (and potentially 1.13).
