### ISSUE TITLE
[1.15.2] Dedicated server crash - Loading errors encountered: [ 	Nifty (nifty) has failed to load correctly ยง7net/minecraft/client/renderer/RenderType

### ISSUE THREAD

**Issue by ProsperCraft** [Andromander/Nifty#21]
Server loads without nifty, with nifty it crashes-

forge-1.15.2-31.1.0
nifty-1.15.2-2.9.jar

Log- https://gist.github.com/ProsperCraft/89c41699e00095bdaa748870933bbd3c

Crash -https://gist.github.com/ProsperCraft/dbf0526b1be4e49638ba7f3e38115319

**Comment by Andromander** [comment]
Fixed and released in 2.9.1
