### ISSUE TITLE
[1.16.3] Client crash - Mod file has mods that were not found.

### ISSUE THREAD

**Issue by ProsperCraft** [Andromander/Nifty#24]
ornamental-1.16.3-4.3.1
Modpack - [TownCraft TWO for 1.16.3](https://www.curseforge.com/minecraft/modpacks/towncraft)
![2020-10-24_08 42 29](https://user-images.githubusercontent.com/4427684/97084584-5ac4db00-15d5-11eb-8c5e-73b51a6ff737.png)
Crash log-
https://gist.github.com/ProsperCraft/390c2f48710a309299f2b09cc23cd4c3

Reproduced with only Ornamental-
![2020-10-24_08 45 03](https://user-images.githubusercontent.com/4427684/97084605-7a5c0380-15d5-11eb-95ea-558fea387427.png)
https://gist.github.com/ProsperCraft/95f08d9f9b05a32f72524cb17afa0a95

**Comment by bessiq** [comment]
Having the same issue. Looks like the `com` folder didn't get packed into the jar.

**Comment by Andromander** [comment]
It's...it's like the entire source was never built?
I've opened up the source file myself, and it's completely empty of actual code. Assets, data, and the mod toml exist, but nothing else.

**Comment by Andromander** [comment]
No code change required, just slapping a computer over the back of the head for not actually copying due to being slow.
