### ISSUE TITLE
[1.16.5] snow "layers" crafted instead of snow slab

### ISSUE THREAD

**Issue by Maks1234Ty** [Andromander/Nifty#31]
![JEI_results](https://user-images.githubusercontent.com/82882440/116563183-14459580-a904-11eb-8669-0936db121179.png)
![CraftingResult](https://user-images.githubusercontent.com/82882440/116563187-1576c280-a904-11eb-9cac-17c7f94c42dc.png)

**Comment by Andromander** [comment]
Duplicate part of #27
