### ISSUE TITLE
Cannot right click animals

### ISSUE THREAD

**Issue by TacocaTYT** [Andromander/Nifty#33]
In a modpack this mod being enabled resulted in animals not being right clickable. THIS MEANS: 
-No Breeding
-No Feeding
-No Shearing
-No Harvesting modded rich clickables
-No CarryOn mod as it wont trigger

**Comment by Andromander** [comment]
Can you give me the whole mod list? This seems highly improbable as I do nothing to the right click function.

It may also be worth linking the full log when you right-click anything else. There could be errors in there, but I wouldn't know as no logs have been provided.

**Comment by TacocaTYT** [comment]
my apologies, two mods were disabled at the same time, this isn't an issue with your mod, rather an issue with a create addon that was accidentally disabled at the same time when we were hunting for this bug.

Have a nice day and sorry for any inconvenience

**Comment by Andromander** [comment]
Oh, in that case then, never mind.
