### ISSUE TITLE
1.18.2 Update possible?

### ISSUE THREAD

**Issue by Stimraug** [Andromander/Nifty#35]
Hello, will Ornamental be updated for 1.18.2? Not to bother you with it, but I have a server dear to me waiting for that compatibility. Perhaps I should not have updated all those mods after all..

Thank you!

**Comment by Andromander** [comment]
I might as well push an update for this at some point to enable 1.18.2 support. Been wrapped up on more complex projects that I've neglected my smaller, more functioning ones.

**Comment by Stimraug** [comment]
Update? :)
